module.exports = {
    1: {
        id: 1,
        q: "What beverage do you prefer the most?",
        qo: "What beverage does {} prefer the most?",
        op: [
            ["Tea", "tea.webp"],
            ["Coffee", "coffee.jpg"],
            ["Water", "water.jpg"],
            ["Milk", "milk.jpg"],
            ["Cold-drinks", "cold-drink.jpg"],
            ["Juice", "juice.jpg"],
        ],
    },
    2: {
        id: 2,
        q: "What is your Birthday month?",
        qo: "What is {}'s Birthday month?",
        op: [
            ["January", null],
            ["February", null],
            ["March", null],
            ["April", null],
            ["May", null],
            ["June", null],
            ["July", null],
            ["August", null],
            ["September", null],
            ["October", null],
            ["November", null],
            ["December", null],
        ],
    },
    3: {
        id: 3,
        q: "What is your favorite color?",
        qo: "What is {}'s favorite color?",
        op: [
            ["black", null],
            ["yellow", null],
            ["red", null],
            ["blue", null],
            ["green", null],
            ["orange", null],
            ["white", null],
            ["pink", null],
            ["violet", null],
            ["Something else", null],
        ],
    },
    4: {
        id: 4,
        q: "Do you like Android or iPhone?",
        qo: "Does {} like Android or iPhone?",
        op: [
            ["Android", "android.jpg"],
            ["iPhone", "iphone.jpg"],
        ],
    },
    5: {
        id: 5,
        q: "Who do you think is better?",
        qo: "Who, according to {}, is better?",
        op: [
            ["Ronaldo", "ronaldo.jpg"],
            ["Messi", "messi.jpg"],
        ],
    },
    6: {
        id: 6,
        q: "Do you like rain or snow?",
        qo: "Does {} like rain or snow?",
        op: [["Rain"], ["snow"]],
    },
    7: {
        id: 7,
        q: "What do you use the most?",
        qo: "Which platform does {} use the most?",
        op: [["WhatsApp"], ["Facebook"], ["Instagram"], ["YouTube"]],
    },
    8: {
        id: 8,
        q: "What type of games do you like?",
        qo: "What type of games does {} like?",
        op: [["Indoor games"], ["Outdoor games"], ["Mobile games"], ["Don't play any games."]],
    },
    9: {
        id: 9,
        q: "Do you like veg or non-veg?",
        qo: "Does {} like veg or non-veg?",
        op: [["veg"], ["non-veg"]],
    },
    10: {
        id: 10,
        q: "Which time of the day do you like?",
        qo: "Which time of the day does {} like?",
        op: [["Morning"], ["Afternoon"], ["Evening"], ["Night"]],
    },
    11: {
        id: 11,
        q: "What type of food do you like?",
        qo: "What type of food does {} like?",
        op: [["Sweet"], ["Spicy"]],
    },
    12: {
        id: 12,
        q: "Which one will you choose?",
        qo: "Which one will {} choose?",
        op: [["beach"], ["hills"]],
    },
    13: {
        id: 13,
        q: "What kind of hair do you like?",
        qo: "What kind of hair does {} like?",
        op: [["Short"], ["Long"]],
    },
    14: {
        id: 14,
        q: "What is your Favourite Ice-Cream?",
        qo: "What is {}'s Favourite Ice-Cream?",
        op: [["Chocolate"], ["Vanilla"], ["Mango"], ["StrawBerry"], ["Butter-Scotch"], ["Pineapple"]],
    },
    15: {
        id: 15,
        q: "What’s your pick: pen or pencil?",
        qo: "What’s {}'s pick: pen or pencil?",
        op: [["Pen"], ["Pencil"], ["Chalk"], ["Typing"]],
    },
    16: {
        id: 16,
        q: "If you win a lottery, What will you do?",
        qo: "If {} wins a lottery, What will {} do?",
        op: [["buy diamonds"], ["invest the money"], ["Go on a world tour"], ["Invest in education"]],
    },
    17: {
        id: 17,
        q: "Which type of shopping do you like?",
        qo: "Which type of shopping does {} like?",
        op: [["online"], ["traditional"]],
    },
    18: {
        id: 18,
        q: "Which weather do you prefer?",
        qo: "Which weather does {} prefer?",
        op: [["Warm"], ["Cool"], ["Rainy"], ["Windy"]],
    },
    19: {
        id: 19,
        q: "How do you travel in your day to day life?",
        qo: "How does {} travel in day to day life?",
        op: [["Bicycle"], ["Car"], ["Motor-Bike"], ["Scooter"], ["Bus"], ["Taxi"], ["Train"], ["Walking"]],
    },
    20: {
        id: 20,
        q: "What do you prefer?",
        qo: "What does {} prefer?",
        op: [["Online class"], ["Offine class"]],
    },
    21: {
        id: 21,
        q: "What is a good school according to you?",
        qo: "What is a good school according to {}?",
        op: [["Where there is no study"], ["Where teachers are the best"], ["Where there is a large playground"]],
    },
    22: {
        id: 22,
        q: "Which one thing you like the most in school?",
        qo: "Which does {} like the most in school?",
        op: [["Learning"], ["Sleeping at back bench"], ["Game period"], ["teachers"], ["talking woth friends"]],
    },
    23: {
        id: 23,
        q: "Have you ever eaten food during lectures?",
        qo: "Has {} ever eaten food during lectures?",
        op: [["yes"], ["no"]],
    },
    24: {
        id: 24,
        q: "Which type of clothes do you prefer in school?",
        qo: "Which type of clothes does {} prefer in school?",
        op: [["Casual dress"], ["school uniform"]],
    },
    25: {
        id: 25,
        q: "Have you ever got into a fight in school?",
        qo: "Has {} ever got into a fight in school?",
        op: [["Yes"], ["No"]],
    },
    26: {
        id: 26,
        q: "Have you ever cheated in exam?",
        qo: "Has {} ever cheated in exam?",
        op: [["Yes"], ["No"]],
    },
    27: {
        id: 27,
        q: "What is your favorite subject?",
        qo: "What is {}'s favorite subject?",
        op: [["Science"], ["Mathematics"], ["History"], ["Drawing/Painting"], ["Geography"], ["Music"], ["Language"], ["everything"], ["something else"]],
    },
    28: {
        id: 28,
        q: "What is your favorite music genre?",
        qo: "What is {}'s favorite music genre?",
        op: [["Rock"], ["Party"], ["Classical"], ["Rap"], ["Bollywood"], ["English songs"]],
    },
};
